name: Compress FFmpeg

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install 7zip
        run: sudo apt update && sudo apt install -y p7zip-full

      - name: Compress Linux build
        run: 7z a -t7z -mx=9 -m0=lzma2 -md=1024m -mmt=on ffmpeg-linux.7z ffmpeg-linux

      - name: Compress Windows build
        run: 7z a -t7z -mx=9 -m0=lzma2 -md=1024m -mmt=on ffmpeg-win.7z ffmpeg-win

      - name: Upload Linux archive
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux
          path: ffmpeg-linux.7z

      - name: Upload Windows archive
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-win
          path: ffmpeg-win.7z
