name: Compress FFmpeg

on:
  push:
    tags:
      - 'v*'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install 7zip
        run: sudo apt update && sudo apt install -y p7zip-full

      - name: Compress Linux build
        run: 7z a -t7z -mx=9 -m0=lzma2 -md=1024m -mmt=on ffmpeg-linux.7z ffmpeg-linux

      - name: Compress Windows build
        run: 7z a -t7z -mx=9 -m0=lzma2 -md=1024m -mmt=on ffmpeg-win.7z ffmpeg-win

      - name: Upload archives to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ffmpeg-linux.7z
            ffmpeg-win.7z
